Bobax 16 modal Skeleton
shipmunkdev/bobax-web pull request #15
Opened 2023-03-18 07:17 UTC by SimonMTan

2023-03-18 08:04 UTC, seintun commented on src/pages/Home/index.tsx
> +      <BobaCustomizeableModal
Use shorter `<CustomizeDrinkModal />`

2023-03-18 08:05 UTC, seintun commented on src/types/common/main.d.ts
> +export interface ModalProps {
`CustomizeDrinkModalProps`

2023-03-18 08:08 UTC, seintun commented on src/components/Card/index.tsx
> +  const customizeBoba = () => {
`handleCustomizeBoba`

2023-03-18 08:08 UTC, seintun commented on src/components/Card/index.tsx
> +  setBobaInfoModal: (bobaInfoModal: BobaProps) => void;
`setCustomizationModal`

2023-03-18 08:08 UTC, seintun commented on src/components/Card/index.tsx
> +    setBobaInfoModal(product);
`setCustomization`

2023-03-20 07:45 UTC, seintun requested changes

2023-03-20 07:45 UTC, seintun commented on src/components/Modal/index.tsx
> +                  checked={milk === 'Organic Whole Milk'}
Hope this is just temporary not hard coded.

2023-03-20 07:45 UTC, seintun commented on src/components/Modal/index.tsx
> +                  label={'Boba($0.75)'}
Can we use existing topping objects from sampleBobaAPI?

2023-03-20 07:45 UTC, seintun commented on src/components/Modal/index.tsx
> +                  id={'default-checkbox'}
Why id isn't unique? Should be utilized for which element is checked kinda like bobax-1, how it passed info for modal

2023-03-20 22:54 UTC, seintun commented
Build pipeline failing from eslint 
```3:54:00 PM: Failed to compile.
3:54:00 PM: 
3:54:00 PM: [eslint]
3:54:00 PM: src/components/Modal/index.tsx
3:54:00 PM:   Line 3:8:  'Col' is defined but never used  @typescript-eslint/no-unused-vars
3:54:00 PM:   Line 5:8:  'Row' is defined but never used  @typescript-eslint/no-unused-vars
3:54:00 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
3:54:00 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
3:54:00 PM: ​
3:54:00 PM:   "build.command" failed                                        
3:54:00 PM: ────────────────────────────────────────────────────────────────
3:54:00 PM: ​
3:54:00 PM:   Error message
3:54:00 PM:   Command failed with exit code 1: yarn build (https://ntl.fyi/exit-code-1)
3:54:00 PM: ​
3:54:00 PM:   Error location
3:54:00 PM:   In Build command from Netlify app:
3:54:00 PM:   yarn build
3:54:00 PM: ​
```

2023-03-20 22:59 UTC, SimonMTan commented on src/components/Card/index.tsx
> +  setBobaInfoModal: (bobaInfoModal: BobaProps) => void;
this is for line 8 right?

2023-03-20 23:08 UTC, seintun commented on src/components/Card/index.tsx
> +  setBobaInfoModal: (bobaInfoModal: BobaProps) => void;
#9 since its talking about Modal

2023-03-21 00:14 UTC, seintun commented on src/components/BobaContainer/index.tsx
> +  setBobaInfoModal: (bobaInfoModal: BobaProps) => void;
`setCustomizationModal`

2023-03-21 00:15 UTC, seintun approved these changes

2023-03-21 00:41 UTC, merged